name: nlrl
channels:
  - conda-forge
  - defaults
channel_priority: strict
dependencies:
  - python=3.11
  - asttokens=3.0.0
  - ipdb=0.13.13
  - ipython=9.1.0
  - numpy=2.2.4
  - sentencepiece=0.2.0
  - pip=25.0
  - pip:
    - accelerate==1.6.0
    - aiohappyeyeballs==2.6.1
    - aiohttp==3.11.18
    - aiosignal==1.3.2
    - annotated-types==0.7.0
    - attrs==25.3.0
    - certifi==2025.1.31
    - charset-normalizer==3.4.1
    - cmake==4.0.0
    - datasets==3.5.0
    - dill==0.3.8
    - filelock==3.13.1
    - frozenlist==1.6.0
    - fsspec==2024.6.1
    - huggingface-hub==0.30.2
    - idna==3.10
    - jinja2==3.1.4
    - jsonschema==4.23.0
    - jsonschema-specifications==2024.10.1
    - markupsafe==2.1.5
    - mistral-common==1.5.4
    - mpmath==1.3.0
    - multidict==6.4.3
    - multiprocess==0.70.16
    - networkx==3.3
    - packaging==25.0
    - pandas==2.2.3
    - peft==0.15.2
    - pillow==11.0.0
    - propcache==0.3.1
    - pstat==0.0.1
    - psutil==7.0.0
    - pyarrow==19.0.1
    - pydantic==2.11.3
    - pydantic-core==2.33.1
    - python-dateutil==2.9.0.post0
    - pytz==2025.2
    - pyyaml==6.0.2
    - referencing==0.36.2
    - regex==2024.11.6
    - requests==2.32.3
    - rpds-py==0.24.0
    - safetensors==0.5.3
    - six==1.17.0
    - sympy==1.13.1
    - tiktoken==0.9.0
    - tokenizers==0.21.1
    - --extra-index-url https://download.pytorch.org/whl/cu126
    - torch==2.6.0+cu126
    - tqdm==4.67.1
    - transformers==4.51.3
    - typing-extensions==4.12.2
    - typing-inspection==0.4.0
    - tzdata==2025.2
    - urllib3==2.4.0
    - xxhash==3.5.0
    - yarl==1.20.0
prefix: C:\Users\SBC98\Anaconda3\envs\nlrl